### ISSUE TITLE
Investigate and Optimise API memory problem

### ISSUE THREAD

**Issue by albertkol** [canonical-web-and-design/ubuntu-com-security-api#42]
## Summary

The API on production has memory problems. FIX IT!

**Comment by anthonydillon** [comment]
What is the justification for the estimate of 18 points? We have no description of that size of task. https://canonical-web-and-design.github.io/practices/project-management/fibonacci-estimation-guide.html

**Comment by albertkol** [comment]
@anthonydillon I estimated it at 13. Initially. Then I worked one extra day, so I added another 5 points to it. That was might thought process behind it.

Reading the page, I think I should have left it to 13.

**Comment by albertkol** [comment]
Closing this issue for now. 

We have fixed the Graylog filters, now we can see all the API requests. Together with the pod metrics, we should be able to troubleshoot easier why memory spikes occur, if or when the will happen again. For now, the API has not misbehaved in 2 weeks.
