### ISSUE TITLE
Groovy marked as `devel` on releases API

### ISSUE THREAD

**Issue by hadasbloom** [canonical-web-and-design/ubuntu-com-security-api#52]
## Summary
When requesting the details on the `Groovy` 20.10 release from the releases API the release is marked as `development=true`.

## Process

1. `curl -X GET "https://ubuntu.com/security/releases/groovy.json" -H "accept: application/json"`
2. Results state `groovy` as in development

## Current and expected result
Groovy to be marked as EOL / development=false.

## Screenshot

![image](https://user-images.githubusercontent.com/73122962/134318496-78d4352c-585f-4d1a-a79d-51c7356d5378.png)

**Comment by nottrobin** [comment]
Thanks for the heads-up @hadasbloom. I've forwarded this issue to the security team, hopefully it'll be updated soon.

**Comment by alexmurray** [comment]
This was fixed by @stevebeattie earlier today:

```shell
curl -s -X GET "https://ubuntu.com/security/releases/groovy.json" -H "accept: application/json" | jq .
```
```json

  "codename": "groovy",
  "development": false,
  "esm_expires": "2021-07-31T00:00:00",
  "lts": false,
  "name": "Groovy Gorilla",
  "release_date": "2020-10-20T00:00:00",
  "support_expires": "2021-07-31T00:00:00",
  "support_tag": "",
  "version": "20.10"
}
```

```shell
curl -s -X GET "https://ubuntu.com/security/releases/impish.json" -H "accept: application/json" | jq .
```
```json

  "codename": "impish",
  "development": true,
  "esm_expires": "2022-07-31T00:00:00",
  "lts": false,
  "name": "Impish Indri",
  "release_date": "2021-10-14T00:00:00",
  "support_expires": "2022-07-31T00:00:00",
  "support_tag": "",
  "version": "21.10"
}

```

**Comment by nottrobin** [comment]
Thanks @alexmurray and @stevebeattie. Closing.
