### ISSUE TITLE
Fix swagger documentation

### ISSUE THREAD

**Issue by albertkol** [canonical-web-and-design/ubuntu-com-security-api#57]
## Summary

We are using an old swagger documentation version. We have to update it.

**Comment by carkod** [comment]
@mtruj013 are you guys using the swagger UI?

**Comment by anthonydillon** [comment]
Are these published somewhere? MAAS is moving to using swagger for reference docs.

**Comment by carkod** [comment]
> Are these published somewhere? MAAS is moving to using swagger for reference docs.

Just asked Albert, this was taken down.

**Comment by stevebeattie** [comment]
For reference, the security team found the swagger documentation UI useful. However, it got taken down because it needed to be upgraded to avoid the cross-site scripting issue in https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx

**Comment by albertkol** [comment]
Documentation has been updated to version v4.12 and it's back live.
